info:
  title: SnapTrade Portfolio API
  version: 0.1.0
servers:
  - url: http://localhost:8000/api
openapi: 3.1.1
paths:
  /holdings/getAll:
    post:
      operationId: holdings.getAll
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accountId:
                  type: string
              required:
                - accountId
              additionalProperties: false
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  positions:
                    type: array
                    items:
                      type: object
                      properties:
                        symbol:
                          type:
                            - object
                            - "null"
                          properties:
                            symbol:
                              type:
                                - object
                                - "null"
                              properties:
                                symbol:
                                  type:
                                    - string
                                    - "null"
                                description:
                                  type:
                                    - string
                                    - "null"
                              required:
                                - symbol
                                - description
                              additionalProperties: false
                          required:
                            - symbol
                          additionalProperties: false
                        units:
                          type:
                            - number
                            - "null"
                        price:
                          type:
                            - number
                            - "null"
                        open_pnl:
                          type:
                            - number
                            - "null"
                        average_purchase_price:
                          type:
                            - number
                            - "null"
                        currency:
                          type:
                            - object
                            - "null"
                          properties:
                            code:
                              type: string
                          required:
                            - code
                          additionalProperties: false
                      required:
                        - symbol
                        - units
                        - price
                        - open_pnl
                        - average_purchase_price
                        - currency
                      additionalProperties: false
                  balances:
                    type: array
                    items:
                      type: object
                      properties:
                        currency:
                          type:
                            - object
                            - "null"
                          properties:
                            code:
                              type: string
                          required:
                            - code
                          additionalProperties: false
                        cash:
                          type:
                            - number
                            - "null"
                        buying_power:
                          type:
                            - number
                            - "null"
                      required:
                        - currency
                        - cash
                        - buying_power
                      additionalProperties: false
                  total_value:
                    type:
                      - number
                      - "null"
                  currency:
                    type:
                      - string
                      - "null"
                required:
                  - positions
                  - balances
                  - total_value
                  - currency
                additionalProperties: false
